name: Example Workflow on Windows

on: [push]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Display GitHub workspace
      run: echo "GitHub workspace is located at ${{ github.workspace }}"
