name: Print Repository Directory

on: [workflow_dispatch]

jobs:
  print-repo-dir:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print repository directory
      run: echo "Repository Directory: ${{ github.workspace }}"
