name: Print Repository Directory

on:
  push:

jobs:
  print-repo-dir:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Print repository directory
        run: echo "Repository Directory: ${{ github.workspace }}"
